# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'queries.ui'
#
# Created: Mon Apr 13 23:42:06 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!
import search_by_name,search_by_address,data_retreived
import DB_manager,options,search_by_id
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_queries(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)
    def setupUi(self, queries):
        queries.setObjectName(_fromUtf8("queries"))
        queries.resize(859, 603)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(queries.sizePolicy().hasHeightForWidth())
        queries.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        queries.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        queries.setFont(font)
        queries.setStyleSheet(_fromUtf8("#queries{\n"
"background-image: url(C:/Python27/ICPMS/your-queries.jpg);\n"
"background-repeat: no-repeat;\n"
"background-position: top right;\n"
"background-size: 250px 250px;\n"
"background-color:white;\n"
"}\n"
"QPushButton {\n"
"color: white;\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #88d, stop: 0.1 #99e, stop: 0.49 #77c, stop: 0.5 #66b, stop: 1 #77c);\n"
"border-width: 1px;\n"
"border-color: #339;\n"
"border-style: solid;\n"
"border-radius: 7;\n"
"padding: 3px;\n"
"font-size: 20px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 50px;\n"
"max-width: 50px;\n"
"min-height: 18px;\n"
"max-height: 20px;\n"
"}\n"
""))
        self.verticalLayout_2 = QtGui.QVBoxLayout(queries)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_17 = QtGui.QLabel(queries)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("NEOTERIQUE"))
        font.setPointSize(20)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout.addWidget(self.label_17)
        self.label_5 = QtGui.QLabel(queries)
        self.label_5.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(queries)
        self.label_6.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.label_3 = QtGui.QLabel(queries)
        self.label_3.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtGui.QLabel(queries)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 251, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.label.setPalette(palette)
        self.label.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtGui.QLabel(queries)
        self.label_4.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.label_7 = QtGui.QLabel(queries)
        self.label_7.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(queries)
        self.label_8.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(queries)
        self.label_9.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_2 = QtGui.QLabel(queries)
        self.label_2.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_10 = QtGui.QLabel(queries)
        self.label_10.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(queries)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_11.setPalette(palette)
        self.label_11.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(queries)
        self.label_12.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(queries)
        self.label_13.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ente_choice_lbl = QtGui.QLabel(queries)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("ZOMBIFIED"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ente_choice_lbl.setFont(font)
        self.ente_choice_lbl.setObjectName(_fromUtf8("ente_choice_lbl"))
        self.horizontalLayout_3.addWidget(self.ente_choice_lbl)
        self.choice_lineEdit = QtGui.QLineEdit(queries)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.choice_lineEdit.setFont(font)
        self.choice_lineEdit.setStyleSheet(_fromUtf8("font-size:18px"))
        self.choice_lineEdit.setObjectName(_fromUtf8("choice_lineEdit"))
        self.horizontalLayout_3.addWidget(self.choice_lineEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_14 = QtGui.QLabel(queries)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("font-size:18px"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_3.addWidget(self.label_14)
        self.dateEdit = QtGui.QDateEdit(queries)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet(_fromUtf8("font-size:18px"))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ok_btn = QtGui.QPushButton(queries)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_btn.sizePolicy().hasHeightForWidth())
        self.ok_btn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(136, 136, 221))
        gradient.setColorAt(0.1, QtGui.QColor(153, 153, 238))
        gradient.setColorAt(0.49, QtGui.QColor(119, 119, 204))
        gradient.setColorAt(0.5, QtGui.QColor(102, 102, 187))
        gradient.setColorAt(1.0, QtGui.QColor(119, 119, 204))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(136, 136, 221))
        gradient.setColorAt(0.1, QtGui.QColor(153, 153, 238))
        gradient.setColorAt(0.49, QtGui.QColor(119, 119, 204))
        gradient.setColorAt(0.5, QtGui.QColor(102, 102, 187))
        gradient.setColorAt(1.0, QtGui.QColor(119, 119, 204))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(136, 136, 221))
        gradient.setColorAt(0.1, QtGui.QColor(153, 153, 238))
        gradient.setColorAt(0.49, QtGui.QColor(119, 119, 204))
        gradient.setColorAt(0.5, QtGui.QColor(102, 102, 187))
        gradient.setColorAt(1.0, QtGui.QColor(119, 119, 204))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(136, 136, 221))
        gradient.setColorAt(0.1, QtGui.QColor(153, 153, 238))
        gradient.setColorAt(0.49, QtGui.QColor(119, 119, 204))
        gradient.setColorAt(0.5, QtGui.QColor(102, 102, 187))
        gradient.setColorAt(1.0, QtGui.QColor(119, 119, 204))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(136, 136, 221))
        gradient.setColorAt(0.1, QtGui.QColor(153, 153, 238))
        gradient.setColorAt(0.49, QtGui.QColor(119, 119, 204))
        gradient.setColorAt(0.5, QtGui.QColor(102, 102, 187))
        gradient.setColorAt(1.0, QtGui.QColor(119, 119, 204))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(136, 136, 221))
        gradient.setColorAt(0.1, QtGui.QColor(153, 153, 238))
        gradient.setColorAt(0.49, QtGui.QColor(119, 119, 204))
        gradient.setColorAt(0.5, QtGui.QColor(102, 102, 187))
        gradient.setColorAt(1.0, QtGui.QColor(119, 119, 204))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(136, 136, 221))
        gradient.setColorAt(0.1, QtGui.QColor(153, 153, 238))
        gradient.setColorAt(0.49, QtGui.QColor(119, 119, 204))
        gradient.setColorAt(0.5, QtGui.QColor(102, 102, 187))
        gradient.setColorAt(1.0, QtGui.QColor(119, 119, 204))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(136, 136, 221))
        gradient.setColorAt(0.1, QtGui.QColor(153, 153, 238))
        gradient.setColorAt(0.49, QtGui.QColor(119, 119, 204))
        gradient.setColorAt(0.5, QtGui.QColor(102, 102, 187))
        gradient.setColorAt(1.0, QtGui.QColor(119, 119, 204))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(136, 136, 221))
        gradient.setColorAt(0.1, QtGui.QColor(153, 153, 238))
        gradient.setColorAt(0.49, QtGui.QColor(119, 119, 204))
        gradient.setColorAt(0.5, QtGui.QColor(102, 102, 187))
        gradient.setColorAt(1.0, QtGui.QColor(119, 119, 204))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.ok_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.ok_btn.setFont(font)
        self.ok_btn.setIconSize(QtCore.QSize(16, 16))
        self.ok_btn.setAutoExclusive(False)
        self.ok_btn.setObjectName(_fromUtf8("ok_btn"))
        self.horizontalLayout.addWidget(self.ok_btn)
        self.back_btn = QtGui.QPushButton(queries)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.back_btn.setFont(font)
        self.back_btn.setObjectName(_fromUtf8("back_btn"))
        self.horizontalLayout.addWidget(self.back_btn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.connect(self.ok_btn, QtCore.SIGNAL("clicked()"),self.ok_btn_clicked)
        self.connect(self.back_btn, QtCore.SIGNAL("clicked()"),self.back_btn_clicked)
        
        self.retranslateUi(queries)
        QtCore.QMetaObject.connectSlotsByName(queries)

    def back_btn_clicked(self):
        self.o=options.Ui_Options_form()
        self.o.show()
        self.close()
    def ok_btn_clicked(self):
        self.choice=int(self.choice_lineEdit.text())
        temp_date=(self.dateEdit.date())
        self.date=str(temp_date.toPyDate())
        if self.choice==1:
            self.sb_name=search_by_name.Ui_Dialog(self.date)
            self.sb_name.show()
            self.close()
        elif self.choice==2:
            self.sb_addr=search_by_address.Ui_Dialog(self.date)
            self.sb_addr.show()
            self.close()
        elif self.choice==3:
            self.sb_id=search_by_id.Ui_Dialog(self.date)
            self.sb_id.show()
            self.close()
            
            
        elif self.choice==4:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            table=self.dbu.GetLast30Visits(self.date)
            self.dr=data_retreived.Ui_Form(table)
            self.dr.show()
            self.close()
        elif self.choice==5:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            table=self.dbu.GetLast30TwoWheelers(self.date)
            self.dr=data_retreived.Ui_Form(table)
            self.dr.show()
            self.close()
        elif self.choice==6:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            table=self.dbu.GetLast30FourWheelers(self.date)
            self.dr=data_retreived.Ui_Form(table)
            self.dr.show()
            self.close()
        elif self.choice==7:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            table=self.dbu.GetLast30Pedestrians(self.date)
            self.dr=data_retreived.Ui_Form(table)
            self.dr.show()
            self.close()
        elif self.choice==8:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            count=self.dbu.GetNumberOfPersons(self.date)
            c=str(count[0])
            QtGui.QMessageBox.information(self,'No of Persons','Total number of persons are: %s '%c)
            self.close()
        elif self.choice==9:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            count=self.dbu.GetNumberOfMales(self.date)
            c=str(count[0])
            QtGui.QMessageBox.information(self,'No of Persons','Total number of male visits are: %s '%c)
            self.close()
        elif self.choice==10:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            count=self.dbu.GetNumberOfFemales(self.date)
            c=str(count[0])
            QtGui.QMessageBox.information(self,'No of Persons','Total number of female visits are: %s '%c)
            self.close()
        elif self.choice==11:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            count=self.dbu.GetNumberOfStudents(self.date)
            c=str(count[0])
            QtGui.QMessageBox.information(self,'No of Persons','Total number of student visits are: %s '%c)
            self.close()
        elif self.choice==12:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            count=self.dbu.GetNumberOfStaff(self.date)
            c=str(count[0])
            QtGui.QMessageBox.information(self,'No of Persons','Total number of staff visits are: %s '%c)
            self.close()
        elif self.choice==13:
            self.dbu=DB_manager.DatabaseUtility('icpms','person','vehicle','purpose')
            count=self.dbu.GetNumberOfOutsiders(self.date)
            c=str(count[0])
            QtGui.QMessageBox.information(self,'No of Persons','Total number of outsiders are: %s '%c)
            self.close()
        else :
            QtGui.QMessageBox.warning(self,'Dang it!!','Invalid Entry!!')
            
            
        
        
            

    def retranslateUi(self, queries):
        queries.setWindowTitle(_translate("queries", "Form", None))
        self.label_17.setText(_translate("queries", "What would you like to know?", None))
        self.label_5.setText(_translate("queries", "1.   Search By Name", None))
        self.label_6.setText(_translate("queries", "2.   Search by Address", None))
        self.label_3.setText(_translate("queries", "3.   Search by ID Number", None))
        self.label.setText(_translate("queries", "4.   Last 30 visits", None))
        self.label_4.setText(_translate("queries", "5.   Last 30 twowheeler visits", None))
        self.label_7.setText(_translate("queries", "6.   Last 30 fourwheeler visits", None))
        self.label_8.setText(_translate("queries", "7.   Last 30 pedestrians", None))
        self.label_9.setText(_translate("queries", "8.   Number of Persons visited the institute on a particular day", None))
        self.label_2.setText(_translate("queries", "9.   Number of males visited the institute on a particular day", None))
        self.label_10.setText(_translate("queries", "10.   Number of females visited the institute on a particular day", None))
        self.label_11.setText(_translate("queries", "11. Number of visits by Students on a particular day", None))
        self.label_12.setText(_translate("queries", "12. Number of visits by Staff on a particular day", None))
        self.label_13.setText(_translate("queries", "13. Number of visits by persons who reside outside the institute area", None))
        self.ente_choice_lbl.setText(_translate("queries", "Enter Your Choice Here:", None))
        self.label_14.setText(_translate("queries", "Date:", None))
        self.ok_btn.setText(_translate("queries", "ok", None))
        self.back_btn.setText(_translate("queries", "Back", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    queries = QtGui.QWidget()
    ui = Ui_queries()
    ui.setupUi(queries)
    queries.show()
    sys.exit(app.exec_())

